### ISSUE TITLE
Parser broken for "ecce"

### ISSUE THREAD

**Issue by CodyTeague** [blagae/open_words#2]
To reproduce:
```
from open_words.parse import Parser

parser = Parser()
parser.parse('ecce')
```

Expected: no exception and word data returned

Actual:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/open_words/parse.py", line 73, in parse
    return {'word': text, 'defs': format_output(parse_result)}
  File "/usr/local/lib/python3.7/site-packages/open_words/formatter.py", line 249, in format_output
    obj = format_morph(obj)
  File "/usr/local/lib/python3.7/site-packages/open_words/formatter.py", line 187, in format_morph
    infl['pos'] = trans_pos(infl['pos'])
  File "/usr/local/lib/python3.7/site-packages/open_words/formatter.py", line 174, in trans_pos
    return parts_of_speech[abb]
KeyError: 'P'
```

**Comment by blagae** [comment]
Thanks for reporting this bug. I have found the issue, it turns out I was parsing the list of unique forms quite naively. I'll see about pushing the bug fix to master asap.

On Jul 26, 2020 04:15, Cody Teague <notifications@github.com> wrote:

To reproduce:

from open_words.parse import Parser

parser = Parser()
parser.parse('ecce')


Expected: no exception and word data

Actual:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/open_words/parse.py", line 73, in parse
    return {'word': text, 'defs': format_output(parse_result)}
  File "/usr/local/lib/python3.7/site-packages/open_words/formatter.py", line 249, in format_output
    obj = format_morph(obj)
  File "/usr/local/lib/python3.7/site-packages/open_words/formatter.py", line 187, in format_morph
    infl['pos'] = trans_pos(infl['pos'])
  File "/usr/local/lib/python3.7/site-packages/open_words/formatter.py", line 174, in trans_pos
    return parts_of_speech[abb]
KeyError: 'P'

**Comment by CodyTeague** [comment]
No problem. Thank you very much for taking a look at this.
